name: sync upstream

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: upstream
      - name: sync
        run: |
          rm -rf ./*
          git clone https://go.googlesource.com/net
          mv ./net/webdav/* .
          rm -rf ./net
      - name: Commit files
        run: |
          git add .
          git config --local user.email "bot@nn.ci"
          git config --local user.name "Bot"
          datetime=$(date +%Y-%m-%d\ %H:%M:%S)
          git commit -m "update webdav upstream at $datetime" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: upstream